### ISSUE TITLE
Deadline 1

### ISSUE THREAD

**Issue by danielaciuperca** [Edward484/ProjectPao#1]
https://github.com/Edward484/ProjectPao/blob/ee02e289411f50032f045a63d35580d41dcbe207/src/ServiceCalculatoare/classes/Angajat.java#L1

Numele pachetului "classes" ar trebui sa fie "model" (pentru ca toate fisierele sunt clase de fapt, nu e corect sa te referi doar la entitati ca fiind clase). 

Numele clasei "main" trebuie sa fie cu litera mare la inceput - "Main".

Nu am vazut nicio implementare de colectie sortata. ArrayList si HashMap nu sunt sortate.

In rest, totul e bine.

**Comment by Edward484** [comment]
solved
